apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        labels.acmecorp.com/costCenter: "TEST"
        labels.acmecorp.com/department: "accounting"
    spec:
      containers:
      - name: nginx
        image: registry.digitalocean.com/matt/nginx:unprivileged_1.20.2
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 101
